# Generated by Django 4.0.6 on 2023-10-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0014_item_stock_quantity_delete_stocknumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restock',
            name='restock_PIC',
        ),
        migrations.AlterUniqueTogether(
            name='restockitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='restockitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='restockitem',
            name='restock',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_on_duty',
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.DeleteModel(
            name='SaleManager',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Restock',
        ),
        migrations.DeleteModel(
            name='RestockItem',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
