# Generated by Django 4.0.6 on 2023-10-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0016_customer_loan_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
