# Generated by Django 4.0.6 on 2023-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0018_alter_payment_amount_alter_payment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Installment', 'Installment'), ('Whole Amount', 'Whole Amount')], default='Installment', max_length=20),
        ),
    ]
