# Generated by Django 4.0.6 on 2023-10-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0021_insection_investment_inpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='esection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmanager.esection'),
        ),
    ]
