# Generated by Django 4.0.6 on 2023-10-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0024_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InPayment',
        ),
    ]
