# Generated by Django 4.0.6 on 2023-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0025_delete_inpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.PositiveIntegerField(choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
