# Generated by Django 4.0.6 on 2023-10-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0026_task_completion_task_notes_task_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)),
                ('date', models.DateField()),
                ('incsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmanager.incsection')),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='section',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loan',
        ),
        migrations.DeleteModel(
            name='InSection',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
