# Generated by Django 4.0.6 on 2023-10-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0029_monthincome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthIncome',
        ),
        migrations.AddField(
            model_name='income',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
