# Generated by Django 4.0.6 on 2023-10-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0031_monthlyincome_remove_income_is_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='InSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmanager.insection')),
            ],
        ),
        migrations.CreateModel(
            name='InPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Installment', 'Installment'), ('Whole Amount', 'Whole Amount')], default='Installment', max_length=20)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmanager.investment')),
            ],
        ),
    ]
