# Generated by Django 4.0.6 on 2023-10-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0033_investment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='compound_frequency',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly'), ('HalfYearly', 'Half-Yearly')], default='Annual', max_length=20),
        ),
    ]
