# Generated by Django 4.0.6 on 2023-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0036_alter_userprofile_annual_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('SIP', 'Systematic Investment Plan'), ('RD', 'Recurring Deposit')], default='SIP', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='sip_rd_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='sip_rd_frequency',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
