# Generated by Django 4.0.6 on 2023-11-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0037_investment_investment_type_investment_sip_rd_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='sip_rd_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='sip_rd_frequency',
        ),
    ]
