# Generated by Django 4.0.6 on 2023-11-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0039_rd_delete_inpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rd',
            name='period_months',
        ),
        migrations.AddField(
            model_name='rd',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='installment_cycle',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('HalfYearly', 'Half-Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='rd',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmanager.rdsection'),
        ),
    ]
