# Generated by Django 4.0.6 on 2024-02-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0041_room_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
