# Generated by Django 3.2.7 on 2024-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0042_remove_task_completion_remove_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
