# Generated by Django 3.2.7 on 2024-02-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0047_booking_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.CharField(choices=[('marriage', 'Marriage'), ('tour', 'Tour'), ('official_work', 'Official_Work'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
