# Generated by Django 3.2.7 on 2024-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0048_booking_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='bride',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='checkin_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='checkout_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='groom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='reserver',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='reserver_aadhar',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='reserver_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='reserver_phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
