# Generated by Django 4.0.6 on 2024-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0050_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit/credit_card', 'Debit/Credit_Card'), ('netbanking', 'NetBanking'), ('upi', 'UPI')], max_length=20, null=True),
        ),
    ]
